# Generated by Django 3.1.1 on 2020-09-12 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='课程代码')),
                ('name', models.CharField(max_length=255, verbose_name='课程名称')),
                ('type', models.CharField(blank=True, max_length=64, verbose_name='课程类型')),
                ('property', models.CharField(blank=True, max_length=64, verbose_name='课程性质')),
                ('department', models.CharField(blank=True, max_length=64, null=True, verbose_name='开课院系')),
                ('credit', models.FloatField(default=0, verbose_name='学分')),
                ('workload', models.PositiveSmallIntegerField(default=0, verbose_name='学时')),
                ('structure', models.CharField(blank=True, max_length=255, null=True, verbose_name='学分组成')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='教学班名称')),
                ('year', models.CharField(max_length=16, verbose_name='学年')),
                ('term', models.CharField(max_length=8, verbose_name='学期')),
                ('main_teacher', models.CharField(max_length=32, verbose_name='主讲教师')),
                ('teachers', models.CharField(max_length=255, verbose_name='教师组成')),
                ('grade', models.CharField(max_length=32, null=True, verbose_name='课程所属年级')),
                ('audience', models.TextField(blank=True, null=True, verbose_name='教学班组成')),
                ('comment', models.TextField(blank=True, verbose_name='选课备注')),
                ('capacity', models.PositiveIntegerField(default=0, verbose_name='选课名额')),
                ('registered_count', models.PositiveIntegerField(default=0, verbose_name='选课人数')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course')),
            ],
        ),
        migrations.CreateModel(
            name='Position',
            fields=[
                ('code', models.CharField(max_length=32, primary_key=True, serialize=False, verbose_name='场地编码')),
                ('name', models.CharField(max_length=32, verbose_name='场地名称')),
                ('type', models.CharField(max_length=32, verbose_name='场地类别')),
                ('capacity', models.PositiveSmallIntegerField(null=True, verbose_name='场地容量')),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weeks', models.PositiveIntegerField()),
                ('day', models.PositiveSmallIntegerField()),
                ('time', models.PositiveIntegerField()),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.lesson')),
                ('position', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.position')),
            ],
        ),
    ]
