# Generated by Django 3.1 on 2020-08-13 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='flag',
            field=models.IntegerField(default=0),
        ),
    ]
